#!/usr/bin/env bash


# load in support functions
. "./utils/shared.sh"

catch_errors

# moxy
#
# main line program which 
function moxy() {
    local -r cmd=${1:-help}
    local -ra rest=("${@:2}")

    # strict error handling by default
    catch_errors

    case $cmd in 
        help) moxy_help;;
        status) moxy_status "${rest[@]}"

    esac

    exit

}

test_if_ready_to_start
moxy "$@"
