#!/usr/bin/env bash

. "./utils/shared.sh"


log "Nodes: $(list "$(findall_in_file "${HOME}/.moxy" "NODE=")" )"
log "Auth: $(pve_auth_header)"
log "Def node: $(get_default_node)"
log "Version: $(pve_version)"
log "Major: $(major_version "$(pve_version)")"
log "Next ID: $(next_container_id "")"

log "Nodes: $(pve_nodes)"
log ""
log "Node Config: $(pve_node_config)"
log ""
log "VMs: $(pve_vm_containers)"
